var AFOA=require('./AFOA_UJ');
var SIIHGGUXGGRJSEGGBRTZGGFS_2=require('./SIIHGGUXGGRJSEGGBRTZGGFS_2')
function SIIHGGUXGGRJSEGGBRTZGGFS(RJSE_KP,VN_1){

var IOWR_1 = AFOA.SIIH_IOWR_FS_XCMJ_RGQH(RJSE_KP);
var RJSE_1 = SIIHGGUXGGRJSEGGBRTZGGFS_2(IOWR_1, VN_1);
return RJSE_1;
}
module.exports=SIIHGGUXGGRJSEGGBRTZGGFS;