var SIIH_IOWR_FS_XCMJ_RGQH=require('./AFOA_BX/SIIH_IOWR_FS_XCMJ_RGQH')
var SIIHGGUXGGRJSEGGBRTZGGFS_2=require('./SIIHGGUXGGRJSEGGBRTZGGFS_2')
function SIIHGGUXGGRJSEGGBRTZGGFS(RJSE_KP,VN_1){

var IOWR_1 = SIIH_IOWR_FS_XCMJ_RGQH(RJSE_KP);
var RJSE_1 = SIIHGGUXGGRJSEGGBRTZGGFS_2(IOWR_1, VN_1);
return RJSE_1;
}
module.exports=SIIHGGUXGGRJSEGGBRTZGGFS;