var ESIH_BRTZ_FS=require('./ESIH_BRTZ_FS')
function VR_TSJQ_BRTZ_FS_ZV_ESIH_BRTZ_FS(IOWR_AFOA) {
    var BQEO=IOWR_AFOA.VR_AFOA_BQEO;
    return ESIH_BRTZ_FS(BQEO);
}
module.exports = VR_TSJQ_BRTZ_FS_ZV_ESIH_BRTZ_FS;