var ESIH_BRTZ_FS=require('./ESIH_BRTZ_FS')
function VR_TSJQ_BRTZ_FS_ZV_ESIH_BRTZ_FS(DIWR_AFOA) {
    var BQEO=DIWR_AFOA.VR_AFOA_BQEO;
    return ESIH_BRTZ_FS(BQEO);
}
module.exports = VR_TSJQ_BRTZ_FS_ZV_ESIH_BRTZ_FS;