var VKVY_LD_TYUB_VN_ZNZK_NQUD =require('./VKVY_LD_TYUB_VN_ZNZK_NQUD');
function WLYC_VKVY_LD_TYUB_VN_ZNZK_NQUD(req,res){
    res.render('VKVY_LD_TYUB_VN_ZNZK_NQUD', {JTYP_1: VKVY_LD_TYUB_VN_ZNZK_NQUD(req.body.VDZV_1)});
}
module.exports=WLYC_VKVY_LD_TYUB_VN_ZNZK_NQUD;