var SIIHGGUXGGRJSEGGBRTZGGFS =require('./SIIHGGUXGGRJSEGGBRTZGGFS');
function WLYC_SIIHGGUXGGRJSEGGBRTZGGFS(req,res){
    res.render('SIIHGGUXGGRJSEGGBRTZGGFS', {JTYP_1: SIIHGGUXGGRJSEGGBRTZGGFS(req.body.VDZV_1)});
}
module.exports=WLYC_SIIHGGUXGGRJSEGGBRTZGGFS;