
var EOSRGGJUZCGGTZGGYJGGEYRH =require('./EOSRGGJUZCGGTZGGYJGGEYRH');
function WLYC_EOSRGGJUZCGGTZGGYJGGEYRH(req,res){
    res.render('EOSRGGJUZCGGTZGGYJGGEYRH', {JTYP_1: EOSRGGJUZCGGTZGGYJGGEYRH(req.body.VDZV_1)});
}
module.exports=WLYC_EOSRGGJUZCGGTZGGYJGGEYRH;